### PR TITLE
Preferably patch non-dotted symbols when more than one matches the prefix

### LINKED ISSUE #1247: Options `--begin` and `--end` patch only the first occurrence of matching symbols
### Describe the bug

Spotted on Alpine while testing `--ttsp`:
```bash
$ objdump -tR /usr/lib/jvm/java-11-amazon-corretto/lib/server/libjvm.so | grep SafepointSynchronize  | grep begin
0000000000287338 l     F .text	0000000000000002              _ZN20SafepointSynchronize5beginEv.cold
0000000000ceaa60 l     F .text	0000000000003365              _ZN20SafepointSynchronize5beginEv
...
```

`Profiler::resolveSymbols` tries resolving `SafepointSynchronize::begin`, which is mangled to `_ZN20SafepointSynchronize5beginE*`, which is then resolved to `_ZN20SafepointSynchronize5beginEv.cold`. The patching then stops, and the other matching symbol is ignored altogether.

`_ZN20SafepointSynchronize5beginEv.cold` is some fallback version of `SafepointSynchronize::begin`:
```bash
(gdb) disass _entry
Dump of assembler code for function _ZN20SafepointSynchronize5beginEv.cold:
   0x00007ffff6eac338 <+0>:	ud2
```
Thus, patching it does not achieve the intended behavior of `--begin`.

This does not happen on e.g. `amazonlinux`:
```bash
$ objdump -tR ./java-17-amazon-corretto.x86_64/lib/server/libjvm.so | grep SafepointSynchronize | grep  begin
0000000000cb5150 l     F .text	000000000000084c              _ZN20SafepointSynchronize5beginEv
```

Thanks @krk for the debugging support.

### Async-profiler version

`master`

### PR DESCRIPTION
**Pull request by fandreuz**
### Description
In this PR I implement the result of the discussion under #1247

### Related issues
Fixes #1247 
Needed by #1226 

### Motivation and context
Dotted symbols are generally less meaningful to be patched than dotted symbols.

### How has this been tested?
`make test-cpp` and
```bash
docker run \
   -it --privileged --rm \
   -v $(pwd):/async-profiler amazoncorretto:11-alpine-jdk 
   sh -c 'apk add --no-cache musl-dev util-linux make gcc g++ linux-headers && \
      cd /async-profiler && \
      rm -rf build && \
      make -j test-java TESTS=jfr'
```

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: src/codeCache.cpp [hunk 1]
```diff
@@ -168,6 +168,20 @@ const void* CodeCache::findSymbolByPrefix(const char* prefix, int prefix_len) {
     return NULL;
 }
 
+const void* CodeCache::findSymbolByPrefix(const char* prefix, int prefix_len, char second_choice_if_contains) {
```
Comment (apangin) [inline src/codeCache.cpp:171]: Another function is redundant: this logic is relevant for all usages of `findSymbolByPrefix`, so I'd modify an existing function instead. Furthermore, `.` character does not need to be configurable, I don't forsee any other usages.

File: src/codeCache.cpp [hunk 2]
```diff
@@ -168,6 +168,20 @@ const void* CodeCache::findSymbolByPrefix(const char* prefix, int prefix_len) {
...
+    int second_choice = -1;
+    for (int i = 0; i < _count; i++) {
+        const char* blob_name = _blobs[i]._name;
+        if (blob_name != NULL && strncmp(blob_name, prefix, prefix_len) == 0) {
+            if (strchr(blob_name, second_choice_if_contains) == NULL) {
```
Comment (apangin) [inline src/codeCache.cpp:176]: `blob_name + prefix_len` to avoid scanning the prefix itself?

File: src/codeCache.cpp [hunk 3]
```diff
@@ -168,6 +168,20 @@ const void* CodeCache::findSymbolByPrefix(const char* prefix, int prefix_len) {
...
+                return _blobs[i]._start;
+            }
+            second_choice = i;
```
[the remark this answers is not in the document]
Comment (fandreuz) [reply src/codeCache.cpp]: 6ea14d2127cd2c84aba23ff925f9f578f888c4a7

File: src/codeCache.cpp (hunk 2 above)
Comment (fandreuz) [reply src/codeCache.cpp]: 70494a561c8882895115806f117746ba9b35318f

File: src/codeCache.cpp [hunk 4]
```diff
@@ -159,13 +159,17 @@ const void* CodeCache::findSymbolByPrefix(const char* prefix) {
 }
 
 const void* CodeCache::findSymbolByPrefix(const char* prefix, int prefix_len) {
+    const void* result = NULL;
     for (int i = 0; i < _count; i++) {
         const char* blob_name = _blobs[i]._name;
         if (blob_name != NULL && strncmp(blob_name, prefix, prefix_len) == 0) {
-            return _blobs[i]._start;
+            result = _blobs[i]._start;
+            if (strchr(blob_name + prefix_len, '.') == NULL) {
```
Comment (apangin) [inline src/codeCache.cpp:167]: Add a short comment describing what we are doing here

File: test/native/symbolsLinuxTest.cpp [hunk 5]
```diff
@@ -60,4 +60,15 @@ TEST_CASE(MappedTwiceAtZeroOffset) {
     hello();
 }
 
+TEST_CASE(MultipleMatchingSymbols) {
+    const void* sym = resolveSymbol("multiplematching.so", "Class::function");
+    ASSERT(sym);
+
+    const void* symOk = resolveSymbol("multiplematching.so", "_ZN5Class8functionEv");
```
Comment (apangin) [inline test/native/symbolsLinuxTest.cpp:67]: `sym_ok` and `sym_cold`

Comment (fandreuz) [reply test/native/symbolsLinuxTest.cpp]: 4fbb4e1dd15c3a4ccfb26e60469aea1abdda6534

File: src/codeCache.cpp (hunk 4 above)
Comment (fandreuz) [reply src/codeCache.cpp:169]: 4fbb4e1dd15c3a4ccfb26e60469aea1abdda6534
